Repository LiteLDev/docs, pull requests merged in 2022-09, with the labels that each got.

#4 Add `setScale` in PlayerAPI & EntityAPI in LLSE
  en/LLSEPluginDevelopment/GameAPI/Entity.md
  en/LLSEPluginDevelopment/GameAPI/Player.md
  zh-Hans/LLSEPluginDevelopment/GameAPI/Entity.md
  zh-Hans/LLSEPluginDevelopment/GameAPI/Player.md
Labels: documentation

#5 Create LLSEJSPlugin.md
  en/LLSEPluginDevelopment/LLSEJSPlugin.md
  en/_sidebar.md
  zh-Hans/LLSEPluginDevelopment/LLSEJSPlugin.md
  zh-Hans/_sidebar.md
Labels: documentation, enhancement

#14 [Docs] Add `PlayerAPI::isSleeping`
  en/LLSEPluginDevelopment/GameAPI/Player.md
  zh-Hans/LLSEPluginDevelopment/GameAPI/Player.md
Labels: enhancement
